---
data_dir: C:\Users\AI\Desktop\student_Manuel\datasets\clean_merged_dataset_all.csv
test_imgs:
- C:\Users\AI\Desktop\student_Manuel\datasets\ARIA\all_images
- C:\Users\AI\Desktop\student_Manuel\datasets\STARE\all-images
- C:\Users\AI\Desktop\student_Manuel\datasets\RIADD_cropped\Training_Set\Training
model_path:  C:\Users\AI\Desktop\student_Manuel\codes\trained_models\Merged\20211007-094150-vit_base_patch16_384/
output_path: C:\Users\AI\Desktop\student_Manuel\codes\trained_models\Merged\20211007-094150-vit_base_patch16_384/
model_name: vit_base_patch16_384
batch_size: 8
num_classes: 15
img_size: 384
start_col: 3
seed: 42
num_workers: 1
pin_memory: True
tta: 1
folds: 5