---
data_dir: C:\Users\AI\Desktop\student_Manuel\datasets\RIADD_cropped\Evaluation_Set\RFMiD_Validation_Labels.csv
test_imgs:
- C:\Users\AI\Desktop\student_Manuel\datasets\RIADD_cropped\Evaluation_Set\Evaluation
model_ckpt: C:\Users\AI\Desktop\student_Manuel\codes\retina_disease_classifier\lightning_logs\version_19\checkpoints\epoch=2-step=287.ckpt
batch_size: 16
num_classes: 29
img_size: 224
start_col: 1
seed: 42
num_workers: 4
pin_memory: True