---
data_dir: C:\Users\AI\Desktop\student_Manuel\datasets\drop_all\20_labels\merged_20_labels_drop_10.0_perc.csv
test_imgs:
- C:\Users\AI\Desktop\student_Manuel\datasets\ARIA\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\STARE\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\RIADD_cropped\Training_Set\Training
model_path: C:\Users\AI\Desktop\student_Manuel\codes\trained_models\merged_all_v2\20211222-231427-vit_base_patch16_384-362233
output_path: C:\Users\AI\Desktop\student_Manuel\codes\trained_models\merged_all_v2\20211222-231427-vit_base_patch16_384-362233
model_name: vit_base_patch16_384
batch_size: 16
num_classes: 20
img_size: 608
start_col: 4
seed: 42
num_workers: 2
pin_memory: True
tta: 5
folds: 0