---
train_data: C:\Users\AI\Desktop\student_Manuel\datasets\synth_data\merged_train_labels.csv
val_data: C:\Users\AI\Desktop\student_Manuel\datasets\synth_data\merged_val_labels.csv
train_imgs:
- C:\Users\AI\Desktop\student_Manuel\datasets\ARIA\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\STARE\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\RIADD_cropped\Training_Set\Training
- C:\Users\AI\Desktop\student_Manuel\datasets\synth_data\all_images
val_imgs:
- C:\Users\AI\Desktop\student_Manuel\datasets\ARIA\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\STARE\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\RIADD_cropped\Training_Set\Training
- C:\Users\AI\Desktop\student_Manuel\datasets\synth_data\all_images
test_imgs:
output_path: C:\Users\AI\Desktop\student_Manuel\codes\trained_models\Synth\
batch_size: 16
lr: 0.00012
num_classes: 34
model: vit_base_patch16_384 
#vit_base_patch16_384 
#efficientnet_b0
img_size: 384
start_col: 5
experiment: 
seed: 42
num_workers: 2
pin_memory: True
epochs: 200
gpus: 1
auto_gpus: False
auto_batch_size: False
auto_lr: True
limit_train_batches: 1.0
limit_val_batches: 1.0
resampling: None
resampling_percentage: 20
folds: 0