---
train_data: C:\Users\AI\Desktop\student_Manuel\datasets\drop_all\20_labels\merged_20_labels_drop_10.0_perc.csv
val_data:
train_imgs:
- C:\Users\AI\Desktop\student_Manuel\datasets\ARIA\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\STARE\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\RIADD_cropped\Training_Set\Training
val_imgs:
- C:\Users\AI\Desktop\student_Manuel\datasets\ARIA\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\STARE\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\RIADD_cropped\Training_Set\Training
test_imgs:
output_path: C:\Users\AI\Desktop\student_Manuel\codes\trained_models\comparison\
batch_size: 16
lr: 0.007
num_classes: 20
model: resnet101
#vgg16
#swin_base_patch4_window12_384_in22k
#deit_base_patch16_384 
#vit_base_patch16_384 
#efficientnet_b0
img_size: 512
start_col: 4
experiment: 
seed: 42
num_workers: 4
pin_memory: True
epochs: 200
gpus: 1
auto_gpus: False
auto_batch_size: False
auto_lr: False
limit_train_batches: 1.0
limit_val_batches: 1.0
resampling: ml_ros
resampling_percentage: 0
folds: 0
loss: BCE
optimizer: SGD
scheduler_threshold: 0.0003
transforms: resnet
automatic_optimization: True
lr_scheduler: polynomiallrdecay