---
data_dir: C:\Users\AI\Desktop\student_Manuel\datasets\drop_all\20_labels\merged_20_labels_drop_10.0_perc.csv
test_imgs:
- C:\Users\AI\Desktop\student_Manuel\datasets\ARIA\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\STARE\all_images_crop
- C:\Users\AI\Desktop\student_Manuel\datasets\RIADD_cropped\Training_Set\Training
model_path: C:\Users\AI\Desktop\student_Manuel\papers\comparison\RIADD_winner\small_model
output_path: C:\Users\AI\Desktop\student_Manuel\papers\comparison\RIADD_winner\small_model
model_name: tf_efficientnet_b5_ns
batch_size: 8
num_classes: 20
img_size: 540
start_col: 4
seed: 42
num_workers: 2
pin_memory: True
tta: 0
folds: 0
transforms: riadd