---
data_dir: /home/kunet.ae/100058256/datasets/clean_merged_dataset_all.csv
train_imgs:
- /home/kunet.ae/100058256/datasets/ARIA/all_images
- /home/kunet.ae/100058256/datasets/STARE/all-images
- /home/kunet.ae/100058256/datasets/RIADD_cropped/Training_Set/Training
val_imgs:
- /home/kunet.ae/100058256/datasets/ARIA/all_images
- /home/kunet.ae/100058256/datasets/STARE/all-images
- /home/kunet.ae/100058256/datasets/RIADD_cropped/Training_Set/Training
test_imgs:
output_path: /home/kunet.ae/100058256/codes/trained_models/merged_all/
batch_size: 16
lr: 0.00012
num_classes: 34
model: vit_base_patch16_224 
#vit_base_patch16_384 
#efficientnet_b0
img_size: 224
start_col: 4
experiment: 
seed: 42
num_workers: 1
pin_memory: True
epochs: 1
gpus: 2
auto_gpus: False
auto_batch_size: False
auto_lr: True
limit_train_batches: 1.0
limit_val_batches: 1.0
resampling: lp_ros