---
train_data: /home/kunet.ae/100058256/datasets/merged_20_labels_drop_10.0_perc.csv
val_data:
train_imgs:
- /home/kunet.ae/100058256/datasets/ARIA/all_images_crop
- /home/kunet.ae/100058256/datasets/STARE/all_images_crop
- /home/kunet.ae/100058256/datasets/RIADD_cropped/Training_Set/Training
val_imgs:
- /home/kunet.ae/100058256/datasets/ARIA/all_images_crop
- /home/kunet.ae/100058256/datasets/STARE/all_images_crop
- /home/kunet.ae/100058256/datasets/RIADD_cropped/Training_Set/Training
test_imgs:
output_path: /home/kunet.ae/100058256/codes/trained_models/merged_all_v2/
batch_size: 16
lr: 0.033
num_classes: 20
model: vit_base_patch16_384 
#vit_base_patch16_384 
#efficientnet_b0
img_size: 384
start_col: 4
experiment: 
seed: 42
num_workers: 4
pin_memory: True
epochs: 200
gpus: -1
auto_gpus: False
auto_batch_size: False
auto_lr: True
limit_train_batches: 1.0
limit_val_batches: 1.0
resampling: ml_ros
resampling_percentage: 30
folds: 0
loss: BCE
optimizer: Ranger
scheduler_threshold: 0.0005
transforms: vgg16