---
data_dir: /home/kunet.ae/100058256/datasets/clean_merged_dataset_all.csv
test_imgs:
- /home/kunet.ae/100058256/datasets/ARIA/all_images
- /home/kunet.ae/100058256/datasets/STARE/all-images
- /home/kunet.ae/100058256/datasets/RIADD_cropped/Training_Set/Training
model_path:  /home/kunet.ae/100058256/codes/trained_models/Merged/20211007-094150-vit_base_patch16_384/
output_path: /home/kunet.ae/100058256/codes/trained_models/Merged/20211007-094150-vit_base_patch16_384/
model_name: vit_base_patch16_384
batch_size: 8
num_classes: 15
img_size: 384
start_col: 3
seed: 42
num_workers: 1
pin_memory: True
tta: 1
folds: 5