---
data_dir: /home/kunet.ae/100058256/datasets/clean_merged_dataset_only_2.csv
test_imgs:
- /home/kunet.ae/100058256/datasets/ARIA/all_images
- /home/kunet.ae/100058256/datasets/STARE/all-images
model_path:  /home/kunet.ae/100058256/codes/trained_models/Merged/20211007-082531-vit_base_patch16_224
output_path: /home/kunet.ae/100058256/codes/trained_models/Merged/20211007-082531-vit_base_patch16_224
model_name: vit_base_patch16_224
batch_size: 16
num_classes: 15
img_size: 224
start_col: 3
seed: 42
num_workers: 4
pin_memory: True
tta: 1
folds: 2